/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class DangKyThamNuoiDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangKyThamNuoiDialog
     */
    public DangKyThamNuoiDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initializeTable();
    }
      private void initializeTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Example data, you can replace this with your actual data
        Object[][] defaultData = {
            {"Phạm Vân Anh", "Nam Định", "03630", "Bạn", "03/04/2023", "23/01/2024", "Nguyễn Tú", "PN0023"},
            
            // Add more rows as needed
        };

        for (Object[] rowData : defaultData) {
            model.addRow(rowData);
        }
    }

    // Rest of your code...

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ĐĂNG KÝ THĂM NUÔI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên phạm nhân :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("**Quy định thăm nuôi.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Ngày trong tuần : Thứ 7 và chủ nhật");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Thời gian : Từ 14h đến 17h");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Id của phạm nhân :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày đăng ký :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Mối quan hệ với phạm nhân :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Đăng ký thăm vào ngày : ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 290, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 300, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 260, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 250, 20));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 190, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 250, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 230, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon11.png"))); // NOI18N
        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon12.png"))); // NOI18N
        jButton1.setText("lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon14.png"))); // NOI18N
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 100, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon13.png"))); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Địa chỉ", "SĐT", "Mối quan hệ", "Ngày đăng ký", "Đk thăm vào ngày", "ID phạm nhân", "id phạm nhân"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 307, 900, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon9.png"))); // NOI18N
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                     addPersonForAdoption();
}        

// Method to handle the addition of information about a person visiting for adoption
private void addPersonForAdoption() {
    // Retrieve the information from the text fields
    String fullName = jTextField1.getText();
    String address = jTextField2.getText();
    String phoneNumber = jTextField3.getText();
    String relationship = jTextField4.getText();
    String registrationDate = jTextField5.getText();
    String visitDate = jTextField6.getText();
    String prisonerName = jTextField7.getText();
    String prisonerId = jTextField8.getText();

    // Validate that all required fields are filled
    if (fullName.isEmpty() || address.isEmpty() || phoneNumber.isEmpty() || relationship.isEmpty() ||
            registrationDate.isEmpty() || visitDate.isEmpty() || prisonerName.isEmpty() || prisonerId.isEmpty()) {
        // Display an error message or handle the validation error as needed
        JOptionPane.showMessageDialog(this, "Yêu cầu nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return; // Do not proceed with adding to the table if validation fails
    }

    // Add the information to the table
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{fullName, address, phoneNumber, relationship, registrationDate, visitDate, prisonerName, prisonerId});

    // Optionally, you can clear the input fields after adding the information
    clearInputFields();

}

// Method to clear the input fields
private void clearInputFields() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
            



     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        saveRegistrationInformation();
    }//GEN-LAST:event_jButton1ActionPerformed
   private void saveRegistrationInformation() {
    // Retrieve the information from the text fields
    String fullName = jTextField1.getText();
    String address = jTextField2.getText();
    String phoneNumber = jTextField3.getText();
    String relationship = jTextField4.getText();
    String registrationDate = jTextField5.getText();
    String visitDate = jTextField6.getText();
    String prisonerName = jTextField7.getText();
    String prisonerId = jTextField8.getText();

    // Validate the input if needed

    // Create a string to represent the registration information
    String registrationInfo = "Họ tên: " + fullName +
                              "\nĐịa chỉ: " + address +
                              "\nSố điện Thoại: " + phoneNumber +
                              "\nMối quan hệ với phạm nhân: " + relationship +
                              "\nNgày Đăng ký: " + registrationDate +
                              "\nĐăng ký thăm ngày: " + visitDate +
                              "\nTên phạm nhân: " + prisonerName +
                              "\nID phạm nhân: " + prisonerId;

    // Display the registration information (you can replace this with your actual saving logic)
    JOptionPane.showMessageDialog(this, registrationInfo, "Registration Information", JOptionPane.INFORMATION_MESSAGE);

    // Optionally, you can perform additional actions such as storing the information in a database
    // For example: databaseManager.saveRegistrationInformation(fullName, address, phoneNumber, ...);
    
    // Clear the input fields after saving
    clearInputFields();
}


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         confirmAndDeleteSelectedRow();              
    }//GEN-LAST:event_jButton2ActionPerformed
    private void confirmAndDeleteSelectedRow() {
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();

    // Check if a row is selected
    if (selectedRowIndex != -1) {
        // Display a confirmation dialog
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        // Check user's choice
        if (choice == JOptionPane.YES_OPTION) {
            // Remove the selected row from the table
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRowIndex);

            // Optionally, you can perform additional actions such as updating your data source or database
        }
    } else {
        // If no row is selected, display a message to inform the user
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.", "Đã chọn hàng để xóa", JOptionPane.WARNING_MESSAGE);
    }
}                           
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                              
    editSelectedRow();             
}                                        

private void editSelectedRow() {
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();

    // Check if a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve the data from the selected row
        String fullName = (String) jTable1.getValueAt(selectedRowIndex, 0);
        String address = (String) jTable1.getValueAt(selectedRowIndex, 1);
        String phoneNumber = (String) jTable1.getValueAt(selectedRowIndex, 2);
        String relationship = (String) jTable1.getValueAt(selectedRowIndex, 3);
        String registrationDate = (String) jTable1.getValueAt(selectedRowIndex, 4);
        String visitDate = (String) jTable1.getValueAt(selectedRowIndex, 5);
        String prisonerName = (String) jTable1.getValueAt(selectedRowIndex, 6);
        String prisonerId = (String) jTable1.getValueAt(selectedRowIndex, 7);

        // Populate the input fields with the selected data
        jTextField1.setText(fullName);
        jTextField2.setText(address);
        jTextField3.setText(phoneNumber);
        jTextField4.setText(relationship);
        jTextField5.setText(registrationDate);
        jTextField6.setText(visitDate);
        jTextField7.setText(prisonerName);
        jTextField8.setText(prisonerId);

        // Optionally, you can provide visual feedback to indicate that the row is being edited
        // For example: change the color of the selected row

        // After editing, you can choose to update the data in the table
        // You can implement a save/update button to save the changes back to the table
        // or automatically save changes when the user modifies the fields and clicks "Sửa".
    } else {
        // If no row is selected, display a message to inform the user
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa.", "Đã chọn hàng để sửa", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyThamNuoiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyThamNuoiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyThamNuoiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyThamNuoiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKyThamNuoiDialog dialog = new DangKyThamNuoiDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

  
  
    
}
